version: "3.9"
services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: remarkpassword
  app:
    build: .
    environment:
      DATABASE_NAME: postgres
    ports:
      - "8080:8080"
    links:
      - "database:database"
    depends_on:
      - database
    volumes:
      - ${PWD}/.env:/app/.env
