nginx:
  image: nginx:latest
  volumes:
    - ./docker/nginx:/etc/nginx/conf.d
    - .:/app
  ports:
    - "80:80"
  links:
    - fpm
fpm:
  image: fpm-mysql-redis
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USERNAME: root
    MYSQL_PASSWORD: root
    MYSQL_DATABASE: remark
    MYSQL_HOST: db
    REDIS_HOST: redis
    REDIS_PREFIX: remark_
  volumes:
    - .:/app
  links:
    - db
    - redis
db:
  image: mariadb
  ports:
    - 3306:3306
  expose:
    - 3306
  volumes:
    - ./docker/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
  environment:
     MYSQL_ROOT_PASSWORD: root
redis:
  image: redis
  ports:
    - 6379:6379
