version: "3.9"
services:
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: remark
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  app:
    build: .dckrz/config/docker/build
    command: "go run main.go"
    ports:
      - "8080:8080"
    links:
      - "database:database"
    depends_on:
      - database
    volumes:
    - ".:/app"
    working_dir: /app
