apiVersion: v2
name: remark-api
description: A Helm chart to run remark-api in Kubernetes
type: application
version: 1.2.0
icon: https://itsmethemojo.github.io/helm-charts/icon.png
sources:
  - https://github.com/itsmethemojo/remark-api
dependencies:
- name: basic-web-app
  version: "1.1.0"
  alias: app
  repository: "https://itsmethemojo.github.io/helm-charts/"
- name: postgresql
  version: 15.5.37
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
